/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SellRouteImport } from './routes/sell'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuctionsRouteImport } from './routes/admin.auctions'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminHorsesRouteImport } from './routes/admin.horses'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AuctionsIdRouteImport } from './routes/auctions.$id'
import { Route as HorsesIndexRouteImport } from './routes/horses.index'
import { Route as HorsesIdRouteImport } from './routes/horses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHorsesRoute = AdminHorsesRouteImport.update({
  id: '/horses',
  path: '/horses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesIndexRoute = HorsesIndexRouteImport.update({
  id: '/horses/',
  path: '/horses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesIdRoute = HorsesIdRouteImport.update({
  id: '/horses/$id',
  path: '/horses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/horses/$id': typeof HorsesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/horses/$id': typeof HorsesIdRoute
  '/admin': typeof AdminIndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/horses': typeof HorsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/horses/$id': typeof HorsesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/register'
    | '/sell'
    | '/admin/auctions'
    | '/admin/clients'
    | '/admin/deals'
    | '/admin/horses'
    | '/admin/requests'
    | '/auctions/$id'
    | '/horses/$id'
    | '/admin/'
    | '/auctions/'
    | '/horses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/sell'
    | '/admin/auctions'
    | '/admin/clients'
    | '/admin/deals'
    | '/admin/horses'
    | '/admin/requests'
    | '/auctions/$id'
    | '/horses/$id'
    | '/admin'
    | '/auctions'
    | '/horses'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/register'
    | '/sell'
    | '/admin/auctions'
    | '/admin/clients'
    | '/admin/deals'
    | '/admin/horses'
    | '/admin/requests'
    | '/auctions/$id'
    | '/horses/$id'
    | '/admin/'
    | '/auctions/'
    | '/horses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SellRoute: typeof SellRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
  HorsesIdRoute: typeof HorsesIdRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  HorsesIndexRoute: typeof HorsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/horses': {
      id: '/admin/horses'
      path: '/horses'
      fullPath: '/admin/horses'
      preLoaderRoute: typeof AdminHorsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/': {
      id: '/horses/'
      path: '/horses'
      fullPath: '/horses/'
      preLoaderRoute: typeof HorsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/$id': {
      id: '/horses/$id'
      path: '/horses/$id'
      fullPath: '/horses/$id'
      preLoaderRoute: typeof HorsesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminHorsesRoute: typeof AdminHorsesRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminHorsesRoute: AdminHorsesRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SellRoute: SellRoute,
  AuctionsIdRoute: AuctionsIdRoute,
  HorsesIdRoute: HorsesIdRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  HorsesIndexRoute: HorsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
